name: check

on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-fmt:
    name: "nix fmt"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ github.token }}
    - uses: cachix/cachix-action@v12
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix fmt

  checks:
    name: a${{ matrix.config.check }} ("  "test  ) ${{ matrix.config.some }}${{ matrix.config.nonexistent }} b ${{ matrix.other }} c (other ${{ matrix.other }})
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ github.token }}
    - uses: cachix/cachix-action@v12
      with:
        name: enarx
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: rustup show
    - run: cargo update
    - run: git add -f Cargo.lock
    - run: nix build -L --show-trace '.#checks.${{ matrix.config.system }}.${{ matrix.config.check }}'
